import gradio as gr
import uuid
from pathlib import Path
from shutil import copytree

from agents.story_agent import StoryAgent
from agents.visual_prompt_agent import VisualPromptAgent
from diffusion.multi_view_generator import MultiViewDiffusionGenerator

# ------------------------------
# FastAPI base URL (3D viewer)
# ------------------------------
VIEWER_BASE_URL = "http://127.0.0.1:8080"



# ------------------------------
# Initialize pipeline components
# ------------------------------
story_agent = StoryAgent()
visual_prompt_agent = VisualPromptAgent()
diffusion_generator = MultiViewDiffusionGenerator()

# ------------------------------
# Core Pipeline function
# ------------------------------
def generate_scene(user_prompt: str):
    """
    Runs story -> visual prompt -> multi-view diffusion
    Then embeds 3D viewer (iframe)
    """
    # Generate unique scene ID
    scene_id = f"scene_{uuid.uuid4().hex[:8]}"

    # Create scene directory
    scene_dir = Path(f"data/scenes/{scene_id}")
    scene_dir.mkdir(parents=True, exist_ok=True)
    # ----------------------------------
    # STEP 6B: Copy placeholder mesh into viewer assets
    # ----------------------------------
    DEMO_ASSET_DIR = Path("viewer/assets/scene")
    TARGET_ASSET_DIR = Path(f"viewer/assets/{scene_id}")

    # Copy demo mesh only once per scene
    if not TARGET_ASSET_DIR.exists():
         copytree(DEMO_ASSET_DIR, TARGET_ASSET_DIR)

    # Step 1: Story Agent
    story_data = story_agent.run(user_prompt)

    # Step 2: Visual Prompt Agent
    visual_prompt = visual_prompt_agent.run(story_data)

    # Step 3: Multi-View Diffusion Generator
    outputs = diffusion_generator.generate(
        visual_prompt=visual_prompt,
        scene_dir=scene_dir
    )

    # Convert image paths to list (for Gradio Gallery)
    image_paths = [
        str(outputs["front"]),
        str(outputs["left"]),
        str(outputs["right"]),
        str(outputs["top"])
    ]

    # Step 4: Embed 3D Viewer (FastAPI-served)
    # Viewer still points to demo scene (will switch to scene_id in Step 6C)
    viewer_html = f"""
    <iframe
    src="{VIEWER_BASE_URL}/index.html?scene_id={scene_id}"
    width="100%"
    height="600"
    style="border:none; background:black;"
    ></iframe>
  """

    return visual_prompt, image_paths, viewer_html

# ------------------------------
# Gradio UI Layout
# ------------------------------
with gr.Blocks(title="AI Filmmaking Copilot") as demo:
    gr.Markdown("# 🎬 AI Filmmaking Copilot")
    gr.Markdown(
        "Story → Visual Prompt → Multi-view Diffusion → **3D Scene Viewer**"
    )

    # User Prompt
    user_prompt = gr.Textbox(
        label="Story Prompt",
        placeholder="A dark cyberpunk alley at night with neon lights and rain",
        lines=3
    ) 
    generate_button = gr.Button("Generate Scene")

    # Visual Prompt Agent Output
    visual_prompt_output = gr.Textbox(
        label="Visual prompt (Generated by Agent)",
        interactive=False,
        lines=3
    )

    # Mutli-view Diffusion Images
    image_gallery = gr.Gallery(
        label="Mutli-view Diffusion Images",
        columns=2,
        height= 300
    )

  # ------------------------------
    # 3D Viewer (Embedded)
    # ------------------------------
    viewer = gr.HTML(
    value="""
    <div style="height:600px; display:flex; align-items:center; justify-content:center; color:#888;">
        3D Viewer will appear here
    </div>
    """,
    label="Final 3D Scene"
  )
    # ------------------------------
    # Wire button click
    # ------------------------------
    generate_button.click(
        fn=generate_scene,
        inputs=user_prompt,
        outputs=[
            visual_prompt_output,
            image_gallery,
            viewer
        ]
    )

if __name__ == "__main__":
    demo.launch()